language: python
python:
    - "3.6"
install:
    - "python setup.py install"
script:
    - "make test"
after_success:
    - codecov
notifications:
    email:
        recipients:
            - "ellisonleao@gmail.com"
